name: Build Docker Images

env:
  DOCKERHUB_TAG: "foorschtbar/routeros-letsencrypt"
  DOCKERHUB_SHORT_DESCRIPTION: "Let's Encrypt for RouterOS Webserver/API"
  DOCKERHUB_README_FILE: "README.md"

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_TAG }}:latest
          platforms: linux/amd64,linux/arm/v7,linux/arm64

      - name: Image digests
        run: |
          echo image digest: ${{ steps.docker_build.outputs.digest }}

  pushreadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
        with:
          destination_container_repo: ${{ env.DOCKERHUB_TAG }}
          provider: dockerhub
          short_description: ${{ env.DOCKERHUB_SHORT_DESCRIPTION }}
          readme_file: ${{ env.DOCKERHUB_README_FILE }}
